### ISSUE TITLE
DevKit.exe doesn't do anything

### ISSUE THREAD

**Issue by Twingamerdudes** [NKHook/NKHook5#15]
**Describe the bug**
So when I run the file, a cmd prompt opens for a milisecond before closing and nothing happens.

**To Reproduce**
1. Download DevKit.exe along with the dlls
2. Put the dlls in the game directory
3. Run DevKit.exe

**Expected behavior**
A setup, or the tool itself should open

**Screenshots**
NaN

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 0.6.0

**Additional context**
Idk if this is just me being dumb.

**Comment by DisabledMallis** [comment]
This is because DevKit.exe is meant to be used within a cmd or powershell window. Use `cd` to navigate to the folder where DevKit.exe is located, and then run `DevKit.exe -h` to view the help menu (or `.\DevKit.exe -h` for powershell)

After you view the help menu, don't forget to run the setup command! Other options won't work if you have not completed the setup.
